"""
Apply labels to raw_comments.csv → dataset.csv
Labels: opinion, hype, spam, nostalgia, criticism
"""
import csv

# {index: (label, notes)}
LABELS = {
    0:   ("nostalgia", "Korean: 'who's here in 2026'"),
    1:   ("spam", "stream call for multiple songs"),
    2:   ("opinion", "specific prediction about award show choreo"),
    3:   ("hype", "year claim, fandom rally"),
    4:   ("nostalgia", "who's here in 2026 time-marker"),
    5:   ("opinion", "specific reaction to Coachella performance"),
    6:   ("hype", "haters returning = achievement framing"),
    7:   ("spam", "stream call embedded in milestone hype"),
    8:   ("spam", "describes own coordinated streaming campaign"),
    9:   ("hype", "non-English milestone excitement"),
    10:  ("spam", "1BILLION challenge participation call"),
    11:  ("opinion", "claim about kpop trajectory — holds without time ref"),
    12:  ("nostalgia", "1 view to 500M journey check-in"),
    13:  ("hype", "milestone record listing, no argument"),
    14:  ("nostalgia", "8th anniversary + milestone celebration"),
    15:  ("spam", "stream KTL call"),
    16:  ("opinion", "specific song elements named: tuning, rap, dance, vocals"),
    17:  ("hype", "comment count flex"),
    18:  ("hype", "trending in Bangladesh milestone"),
    19:  ("spam", "stream Solo promotion"),
    20:  ("hype", "KTL view count update"),
    21:  ("spam", "1B mission call for 2019"),
    22:  ("hype", "reply fragment"),
    23:  ("nostalgia", "7 years ago + sad update about 1B"),
    24:  ("hype", "gibberish reply"),
    25:  ("spam", "promote Jennie Solo"),
    26:  ("spam", "promote Jennie Solo"),
    27:  ("criticism", "dismissive of fan behavior"),
    28:  ("hype", "reply confusion"),
    29:  ("criticism", "non-English dismissive comment"),
    30:  ("spam", "start streaming now"),
    31:  ("spam", "stream Solo call"),
    32:  ("hype", "blinks are powerful motivational"),
    33:  ("spam", "go for 1 billion"),
    34:  ("spam", "less than 650k go blinks"),
    35:  ("spam", "str3am 800M"),
    36:  ("hype", "non-English fandom hearts"),
    37:  ("hype", "agreement reply"),
    38:  ("hype", "2.3B milestone celebration"),
    39:  ("spam", "stream Jennie Solo"),
    40:  ("spam", "1Billion fighting call"),
    41:  ("spam", "str3am Stay 200m"),
    42:  ("hype", "2.2 and 2.4B love update"),
    43:  ("hype", "can't wait for BP + RV interaction"),
    44:  ("hype", "wants to see BTS react"),
    45:  ("hype", "specific member excitement"),
    46:  ("hype", "waiting for BTS reaction"),
    47:  ("hype", "can't wait"),
    48:  ("hype", "wants Lisa to show break dance"),
    49:  ("hype", "wants to see reaction"),
    50:  ("hype", "predicts BTS will dance to whole song"),
    51:  ("hype", "can't wait"),
    52:  ("hype", "let's see comment"),
    53:  ("hype", "agreement"),
    54:  ("hype", "complimenting username"),
    55:  ("criticism", "labeling someone a hater"),
    56:  ("hype", "non-English laughter"),
    57:  ("spam", "promoting own cover video"),
    58:  ("hype", "wants Jennie rap reaction"),
    59:  ("hype", "agreement reply"),
    60:  ("hype", "advance thinking joke"),
    61:  ("hype", "references other songs' dances"),
    62:  ("hype", "yeah"),
    63:  ("hype", "typo correction"),
    64:  ("hype", "asks about award show"),
    65:  ("hype", "references past performances"),
    66:  ("hype", "will be more interesting than my life joke"),
    67:  ("spam", "promoting own cover"),
    68:  ("hype", "emoji reply"),
    69:  ("hype", "notice you everywhere reply"),
    70:  ("hype", "incomplete reply"),
    71:  ("hype", "heart emoji"),
    72:  ("hype", "praying for Lisa break dance at awards"),
    73:  ("hype", "reply joke about mom name"),
    74:  ("hype", "excited reply"),
    75:  ("hype", "I could just imagine"),
    76:  ("hype", "coincidence while reading comments"),
    77:  ("hype", "good luck for friend performing"),
    78:  ("spam", "stream for 1.5B"),
    79:  ("spam", "multi-song stream targets"),
    80:  ("hype", "true agreement"),
    81:  ("hype", "non-English don't understand"),
    82:  ("hype", "non-English fan greeting to members"),
    83:  ("hype", "non-English reply"),
    84:  ("hype", "non-English reply to username"),
    85:  ("hype", "reply to username only"),
    86:  ("hype", "can't wait exclamation"),
    87:  ("spam", "stream 2B"),
    88:  ("hype", "references BTS jamming to BP songs"),
    89:  ("hype", "you're a psychic"),
    90:  ("hype", "defending Jennie"),
    91:  ("hype", "Romanian blink flag"),
    92:  ("hype", "BITR slogan"),
    93:  ("hype", "still listening exclamation"),
    94:  ("nostalgia", "finally an old comment"),
    95:  ("hype", "exactly reply"),
    96:  ("hype", "non-English"),
    97:  ("criticism", "BLACKPINK should disband, TWICE is better"),
    98:  ("criticism", "counter-attack on charts claim"),
    99:  ("spam", "buy album + vote call"),
    100: ("hype", "yes please reply"),
    101: ("hype", "yes reply"),
    102: ("hype", "non-English exclamation"),
    103: ("spam", "vote BLACKPINK billboard stylized"),
    104: ("criticism", "its not a masterpiece"),
    105: ("criticism", "wtf reaction to hate"),
    106: ("opinion", "personal journey into kpop through this song"),
    107: ("hype", "non-English fan of members"),
    108: ("spam", "vote MMA everyday call"),
    109: ("hype", "non-English I love Lisa"),
    110: ("spam", "stream for 1.6B"),
    111: ("opinion", "quoting Jennie lyric as statement"),
    112: ("hype", "haters bark BP rises"),
    113: ("criticism", "you are barking always comeback"),
    114: ("opinion", "argument that haters can't sing while dancing"),
    115: ("nostalgia", "they were back when we reached 800M"),
    116: ("hype", "haters gonna hate BP gonna slay"),
    117: ("spam", "1 BILLION LETS GO"),
    118: ("hype", "non-English blackpink is cool"),
    119: ("hype", "non-English reply"),
    120: ("hype", "haters spotted + thanks for streaming irony"),
    121: ("hype", "reply"),
    122: ("opinion", "observation that hate = streaming = views"),
    123: ("hype", "reply"),
    124: ("hype", "profile photo observation"),
    125: ("spam", "stream + leave comments coordination post"),
    126: ("hype", "My name is Hater joke"),
    127: ("hype", "non-English"),
    128: ("hype", "non-English"),
    129: ("hype", "non-English she is beautiful"),
    130: ("hype", "reply"),
    131: ("hype", "blackpink is untouchable"),
    132: ("hype", "you are cutes and beautiful"),
    133: ("hype", "BLACKPINK CUTEEEES"),
    134: ("hype", "yes we are back reply"),
    135: ("hype", "1B views argument reply"),
    136: ("opinion", "argument: 10M fans × 100 views = 1B is not organic"),
    137: ("hype", "asking if they stan"),
    138: ("spam", "BREAK THE RECORD call"),
    139: ("hype", "YESSS reply"),
    140: ("hype", "yesss reply"),
    141: ("hype", "yes we are crazy"),
    142: ("hype", "that's how powerful blinks"),
    143: ("hype", "what's the current record question"),
    144: ("hype", "lets hope it keeps pace"),
    145: ("hype", "lovesick girls 10M in 53 min BITR"),
    146: ("hype", "BTS + BP mixed slogan"),
    147: ("hype", "yes I stream like crazy"),
    148: ("hype", "dont hate just love plea"),
    149: ("hype", "reply"),
    150: ("spam", "asking for streaming guide"),
    151: ("criticism", "donald trump username — Excuse me reaction"),
    152: ("criticism", "calling out troll behavior"),
    153: ("opinion", "defending own position with specific rebuttals"),
    154: ("criticism", "blackpink can't make it to the charts"),
    155: ("hype", "shouldn't have laughed reaction"),
    156: ("hype", "wtf reaction"),
    157: ("criticism", "blackpink is just a marketing strategy — comparative put-down"),
    158: ("criticism", "twice outsells BP 4x, specific stat-based criticism"),
    159: ("opinion", "defending ARMYs from toxic label with argument"),
    160: ("hype", "seriously bruh"),
    161: ("criticism", "worldwide group but worse sales — specific criticism"),
    162: ("criticism", "can't reach charts without feature — specific criticism"),
    163: ("criticism", "stating facts about BTS/Twice numbers being higher"),
    164: ("opinion", "ASTRO comparison — not comparing, just noting"),
    165: ("criticism", "dismissing irrelevant comment"),
    166: ("spam", "bot gibberish"),
    167: ("hype", "non-English Thai"),
    168: ("hype", "non-English Korean fan expressing love"),
    169: ("spam", "vote BLACKPINK billboard stylized"),
    170: ("hype", "non-English Korean reply"),
    171: ("hype", "non-English French"),
    172: ("hype", "Lisa FIFA 2026 excitement"),
    173: ("hype", "loving Lisa new song reply"),
    174: ("hype", "ugh your mind is powerful"),
    175: ("hype", "we weren't raised as weaklings"),
    176: ("hype", "trying to bring peace between fandoms"),
    177: ("hype", "community care message to fellow streamer"),
    178: ("hype", "thank you I'm fine reply"),
    179: ("hype", "you are amazing"),
    180: ("hype", "take care get some rest"),
    181: ("hype", "awww thanks"),
    182: ("spam", "vote on vlive embedded in care message"),
    183: ("hype", "thank you love reply"),
    184: ("hype", "emoji reply"),
    185: ("hype", "wish you the best"),
    186: ("hype", "get enough sleep health first"),
    187: ("hype", "happy new year blinks"),
    188: ("spam", "keep voting reply"),
    189: ("hype", "heart emoji"),
    190: ("hype", "non-English"),
    191: ("hype", "we are getting there let's go"),
    192: ("hype", "lets go blinks"),
    193: ("hype", "challenge accepted"),
    194: ("nostalgia", "time traveller reporting 2.3B future"),
    195: ("hype", "top fan message to BP"),
    196: ("hype", "2B milestone excitement"),
    197: ("hype", "2B never so happy being a blink"),
    198: ("hype", "non-English"),
    199: ("hype", "2.3B update"),
    200: ("hype", "streaming mechanics question"),
    201: ("spam", "streaming instructions — how to get views to count"),
    202: ("hype", "I'm Jisoo I'm okay joke reply"),
    203: ("hype", "challenge accepted"),
    204: ("hype", "I'm the 1.1K like milestone"),
    205: ("spam", "stream playing with fire"),
    206: ("hype", "I like your dance Jisoo"),
    207: ("hype", "non-English"),
    208: ("hype", "now 2 billion"),
    209: ("nostalgia", "after 6 years now 2B"),
    210: ("spam", "go to 3 billion stream hard"),
    211: ("hype", "me — Taylor Swift joke"),
    212: ("hype", "emoji + timestamp"),
    213: ("nostalgia", "here with them from 500M to 1B"),
    214: ("spam", "me still streaming for 1B"),
    215: ("nostalgia", "here after 1.4B views"),
    216: ("spam", "road to 2B milestone chain"),
    217: ("hype", "1.4B so proud of girls"),
    218: ("hype", "1.4B views now"),
    219: ("hype", "me tooooo"),
    220: ("nostalgia", "here after 1.4B"),
    221: ("hype", "heyyooo greeting"),
    222: ("nostalgia", "here since 23k views"),
    223: ("hype", "1.4B views update"),
    224: ("nostalgia", "here at 1.4B"),
    225: ("nostalgia", "didn't expect 1B, here now"),
    226: ("nostalgia", "here since 1 view to 1.4B"),
    227: ("hype", "wut reply"),
    228: ("hype", "I want more"),
    229: ("nostalgia", "here after 2B"),
    230: ("hype", "first kpop group to hit 1B and 2B"),
    231: ("hype", "milestone comparison reply"),
    232: ("hype", "now 2.2B haha"),
    233: ("hype", "reply about not 400M"),
    234: ("spam", "keep on streaming"),
    235: ("spam", "go for 400M"),
    236: ("spam", "stream AIIYL first"),
    237: ("spam", "asking ARMY to cross-stream for BTS"),
    238: ("hype", "good luck to y'all"),
    239: ("spam", "streaming afiyl"),
    240: ("hype", "I'll try reply"),
    241: ("spam", "army wants dna 500M cross-stream"),
    242: ("hype", "non-English Polish"),
    243: ("criticism", "twice gonna beat them 😔"),
    244: ("spam", "keep streaming two devices"),
    245: ("hype", "avoid negativity, we did our best"),
    246: ("hype", "don't lose hope we can do this"),
    247: ("criticism", "TWICE is the first"),
    248: ("hype", "non-English"),
    249: ("hype", "never reply"),
    250: ("hype", "2B biggest girl group"),
    251: ("spam", "that's why I came to stream today"),
    252: ("spam", "keep str3aming everyone"),
    253: ("hype", "yasss agreement"),
    254: ("hype", "how to do it question"),
    255: ("criticism", "Despacito still rocks — this isn't possible"),
    256: ("criticism", "thank u next still the best dismissal"),
    257: ("spam", "str3am 1.7B coming"),
    258: ("criticism", "can smell jealousy"),
    259: ("hype", "that's why 1.7B views rebuttal"),
    260: ("criticism", "your faves are a flop"),
    261: ("opinion", "armies hating but still streaming — observation about behavior"),
    262: ("hype", "clarification I love Lisa"),
    263: ("opinion", "fanwars in comments are ridiculous — meta-observation"),
    264: ("opinion", "no group is equal they excel in different things — substantive argument"),
    265: ("hype", "Korean hello let's be friends"),
    266: ("hype", "Rossa I love you"),
    267: ("opinion", "counter-argument about Dynamite vs DDDD views with specific stats"),
    268: ("hype", "guys don't fight both groups are awesome"),
    269: ("hype", "done reply"),
    270: ("hype", "going to be first kpop 1B, not ordinary"),
    271: ("opinion", "explains why BP has more views: fandom streams instead of commenting"),
    272: ("hype", "2.3M comments exclamation"),
    273: ("hype", "please don't talk about other groups here"),
    274: ("hype", "I don't care reply"),
    275: ("hype", "go check BTS comment section"),
    276: ("opinion", "argument: I don't bother ARMYs so why are they here?"),
    277: ("hype", "no need to mention BTS"),
    278: ("hype", "please don't cause arguments"),
    279: ("hype", "BTS stats flex"),
    280: ("criticism", "how many subscribers does bts have snarky"),
    281: ("hype", "please don't talk other groups"),
    282: ("hype", "I checked and want to go"),
    283: ("hype", "oppa will be your husband joke"),
    284: ("criticism", "lol keep dreaming sweety dismissal"),
    285: ("hype", "what exclamation"),
    286: ("hype", "BLACKPINK will slay the world"),
    287: ("hype", "wowww"),
    288: ("hype", "really WOWWW"),
    289: ("hype", "I'm serious exclamation"),
    290: ("hype", "very amazing"),
    291: ("hype", "WOW"),
    292: ("hype", "daebak"),
    293: ("hype", "wow really I'm happy"),
    294: ("opinion", "fact-checking: no Bangladesh on YouTube location list"),
    295: ("hype", "I am from Bangladesh too"),
    296: ("hype", "really Queens exclamation"),
    297: ("hype", "unbelievable want to cry"),
    298: ("hype", "seriously after 3 weeks"),
    299: ("hype", "whatever I swear"),
    300: ("spam", "YG prepare poster 800M + 1B str3am call"),
    301: ("hype", "Black Pink Fanz Hit Here"),
    302: ("nostalgia", "8 years ago can't believe 2018 is 8 years ago"),
    303: ("spam", "MONSTER speed coordination across timezones"),
    304: ("nostalgia", "who's here after comeback poster"),
    305: ("hype", "waiting for Blackpink House ep 12"),
    306: ("nostalgia", "2026 getting flashbacks of peak kpop era during covid"),
    307: ("spam", "WHO WANT TO MAKE 2019 BLACKPINK'S YEAR call"),
    308: ("hype", "streams at 1am before class can't sleep"),
    309: ("spam", "daily view tracking coordination post"),
    310: ("spam", "operation save money for album + stream"),
    311: ("opinion", "never forget the group that started the billion era — historical claim"),
    312: ("hype", "400M tonight thanks to all fandoms"),
    313: ("hype", "popped in recommended from Queen video"),
    314: ("spam", "multi-song 1B goals list"),
    315: ("hype", "12.2M Spotify listeners flex"),
    316: ("nostalgia", "was here from Spanish songs era to 1.4B"),
    317: ("opinion", "explains why DDDD gets more views than AIIYL — audience analysis"),
    318: ("spam", "vote BP Super Bowl halftime show"),
    319: ("hype", "ILL FRICKING TRY"),
    320: ("spam", "Twitter 24-hour project coordination"),
    321: ("nostalgia", "SEVEN YEARS AGO?! shock"),
    322: ("hype", "yes reply"),
    323: ("hype", "omg reply"),
    324: ("nostalgia", "are you still listening after 7 years"),
    325: ("nostalgia", "hello from 2026"),
    326: ("nostalgia", "are you alive, comment is 7 years old"),
    327: ("spam", "BLINKS watch new song GO"),
    328: ("hype", "okkk reply"),
    329: ("hype", "always here"),
    330: ("hype", "non-English present reply"),
    331: ("hype", "meeeee exclamation"),
    332: ("hype", "that's so real bro"),
    333: ("hype", "South Americans going to sleep lol"),
    334: ("hype", "here bcs bpbillboard"),
    335: ("spam", "fighting str3amin for queens"),
    336: ("spam", "been str3amin all day"),
    337: ("hype", "thank you fam fighting"),
    338: ("hype", "we can do this for queens"),
    339: ("hype", "Australia only 25M people priority joke"),
    340: ("hype", "streaming mechanics question playlist"),
    341: ("spam", "it won't count on playlist — streaming advice"),
    342: ("spam", "gibberish"),
    343: ("hype", "you forgot Europeans"),
    344: ("hype", "Arab here"),
    345: ("hype", "Bengalis too"),
    346: ("hype", "what about Africa"),
    347: ("hype", "forgot Philippines"),
    348: ("hype", "Philippines is in Asia"),
    349: ("hype", "non-English Thai"),
    350: ("hype", "non-English Thai"),
    351: ("spam", "str34m HYLT"),
    352: ("hype", "non-English Spanish"),
    353: ("hype", "non-English I am blink army and uniter"),
    354: ("hype", "I'm Jisoo I'm okay role-play"),
    355: ("hype", "aren't we all reply"),
    356: ("hype", "its coming soon lets wait"),
    357: ("criticism", "if YG promised it don't expect much — credibility criticism"),
    358: ("hype", "yo same tho"),
    359: ("nostalgia", "half year and still waiting"),
    360: ("hype", "whole blink nation waiting"),
    361: ("hype", "may release on 2nd anniversary"),
    362: ("hype", "all blinks are waiting"),
    363: ("hype", "been waiting too"),
    364: ("hype", "MY LIFEU WANT TO WATCH BP HOUSE"),
    365: ("hype", "forgot we have to wait for BP House"),
    366: ("spam", "go for 200M views call"),
    367: ("hype", "we are all waiting"),
    368: ("hype", "meeeeeh"),
    369: ("criticism", "in a sea of thirsty fans you're the only one — dismissive"),
    370: ("hype", "everyone almost forgot about that"),
    371: ("hype", "now waiting for 24/365 last episode"),
    372: ("hype", "lmao if this isn't me"),
    373: ("nostalgia", "I really miss that era"),
    374: ("hype", "blackpink has owned every year in my heart"),
    375: ("hype", "me too fam fighting"),
    376: ("hype", "we all want fighting fam"),
    377: ("hype", "non-English love"),
    378: ("hype", "see it's 1.5B now"),
    379: ("hype", "but now it's 1.6B"),
    380: ("spam", "2B is coming stream harder"),
    381: ("hype", "yesss"),
    382: ("hype", "me fighting blinks"),
    383: ("nostalgia", "am only I from the future"),
    384: ("hype", "future streaming plan"),
    385: ("hype", "every year are our"),
    386: ("hype", "you are so cute"),
    387: ("opinion", "blackpink is my rest area — specific metaphor for the music's effect"),
    388: ("hype", "get some rest reply"),
    389: ("hype", "I love you blackpink"),
    390: ("hype", "my crush is blackpink"),
    391: ("hype", "take care of health to fight haters"),
    392: ("hype", "blackpink in your area tagline"),
    393: ("hype", "so proud let's go fam"),
    394: ("hype", "thanks for today blink"),
    395: ("hype", "we're amazing blinks I'm proud"),
    396: ("hype", "back from 2M views exclamation"),
    397: ("spam", "let's gain +2M per day call"),
    398: ("spam", "2m daily views back keep streaming for 1B"),
    399: ("spam", "keep streaming 2M everyday"),
    400: ("hype", "non-English Vietnamese"),
    401: ("hype", "we are doing great"),
    402: ("opinion", "commentary on copyright strike situation affecting views"),
    403: ("hype", "report + so sad reaction"),
    404: ("hype", "report + so sad reaction"),
    405: ("hype", "non-English reaction"),
    406: ("spam", "KEEP BLACKPINK STRONG IN PHYSICAL AND DIGITAL"),
    407: ("hype", "why not buy mini album — encouragement"),
    408: ("hype", "bought 20 copies can't wait for full album"),
    409: ("opinion", "prefers digital over physical — reasoned preference"),
    410: ("spam", "help us spread the news call"),
    411: ("hype", "I MUST BUY FIRST STUDIO ALBUM"),
    412: ("hype", "next comeback excitement"),
    413: ("hype", "I'm ready to buy"),
    414: ("hype", "bought 10 copies YG stan"),
    415: ("hype", "BLACKPINK emoji exclamation"),
    416: ("hype", "OT4 is important message"),
    417: ("hype", "go buy the album we have now"),
    418: ("hype", "now they have album"),
    419: ("nostalgia", "2 years later they got full album"),
    420: ("hype", "got job to buy BP albums"),
    421: ("hype", "I love your energy reply"),
    422: ("hype", "I think so too reply"),
    423: ("hype", "have album with Jennie photocard"),
    424: ("hype", "difference between physical and digital question"),
    425: ("opinion", "explains physical vs digital album difference clearly"),
    426: ("hype", "BP won Best Dance Video at Mtv VMA Japan 2018"),
    427: ("opinion", "sharing rule about EP needing 6 songs for nomination"),
    428: ("hype", "yes BLACKPINK QUEENS reply"),
    429: ("opinion", "new kpop fan entry story through DDDD"),
    430: ("hype", "explaining what Twice is"),
    431: ("spam", "stream AIIYL in Indonesian"),
    432: ("hype", "DDDD now #1 in physical sales question"),
    433: ("hype", "digital points question"),
    434: ("opinion", "sharing specific digital sales stats for BP"),
    435: ("spam", "save money for comeback + stream Dua Lipa collab call"),
    436: ("hype", "Dua Lipa collab excitement"),
    437: ("hype", "BLACKPINK IS THE REVOLUTION slogan"),
    438: ("hype", "BLACKPINK BIANCA"),
    439: ("hype", "non-English"),
    440: ("hype", "non-English reply"),
    441: ("opinion", "explains Twice had more albums before debut so comparison unfair"),
    442: ("hype", "army and blink"),
    443: ("hype", "Igot7s were here question"),
    444: ("hype", "1 billion now"),
    445: ("hype", "QUEEN title list for each member"),
    446: ("hype", "Army Blink Once"),
    447: ("hype", "ON IT reply"),
    448: ("nostalgia", "hello everyone I am from the future"),
    449: ("hype", "army supporting BP too"),
    450: ("spam", "support Ikon stream Goodbye road"),
    451: ("spam", "gibberish"),
    452: ("hype", "1B views now"),
    453: ("hype", "non-English Spanish fandom list"),
    454: ("hype", "non-English"),
    455: ("hype", "non-English"),
    456: ("nostalgia", "amount of views then vs now"),
    457: ("hype", "what about STAYs and ATINYs"),
    458: ("criticism", "your fandom can't even help itself"),
    459: ("hype", "U forgot stay"),
    460: ("hype", "we are BTS army, never competition"),
    461: ("spam", "STREAMING DDU DU DDU DU FOR MOST VIEWED KPOP"),
    462: ("hype", "non-English"),
    463: ("hype", "non-English"),
    464: ("spam", "stream Jennie solo dance practice to 200M"),
    465: ("hype", "I am an armlinnce"),
    466: ("hype", "blinks did that ourselves"),
    467: ("hype", "EXO-L and BLINK here"),
    468: ("hype", "I'm an ARMYBLINK"),
    469: ("hype", "multifandom list"),
    470: ("hype", "Midzy, stay, deobi question"),
    471: ("hype", "maybe u forgot blinks"),
    472: ("hype", "non-English"),
    473: ("hype", "army supporting both BTS and BP"),
    474: ("hype", "1.5B road to 1.6B"),
    475: ("hype", "non-English Thai"),
    476: ("hype", "non-English reply"),
    477: ("opinion", "clever: in recommended after Queen bc BP are queens"),
    478: ("hype", "hahaha nice Queen fan reply"),
    479: ("hype", "what do you think question"),
    480: ("hype", "yes what do you think reply"),
    481: ("hype", "BECAUSE THEY ARE THE QUEENS"),
    482: ("hype", "BLACKPINK IN YOUR AREA"),
    483: ("hype", "enjoy the music reply"),
    484: ("hype", "non-English Thai"),
    485: ("hype", "enjoy the music"),
    486: ("hype", "they appear bc they are queens"),
    487: ("hype", "thanks for watching"),
    488: ("hype", "I was listening to bohemian rhapsody"),
    489: ("hype", "yeaaa reply"),
    490: ("criticism", "I personally do not like this song nor blackpink — preference disclaimer"),
    491: ("hype", "your music genre is different reply"),
    492: ("hype", "emoji reply"),
    493: ("spam", "recommending koplo cover"),
    494: ("hype", "they're going so far proud blink"),
    495: ("hype", "we need more armys like you"),
    496: ("hype", "there are lots of armys like that"),
    497: ("hype", "I am one too"),
    498: ("criticism", "at least try to be original don't copy comments"),
    499: ("spam", "spreading comment to stream AIIYL"),
    500: ("hype", "at least give credits to owner"),
    501: ("hype", "who's the owner question"),
    502: ("spam", "spreading goals on ig and yt"),
    503: ("hype", "okay reply"),
    504: ("spam", "long gibberish string — bot"),
    505: ("spam", "long o-p gibberish string — bot"),
    506: ("spam", "VOTE Asia Artist Awards call"),
    507: ("nostalgia", "attendance check January 6 2019"),
    508: ("nostalgia", "8 years old today will never get old — anniversary"),
    509: ("spam", "COME TO BRAZIL concert call"),
    510: ("hype", "non-English stream BP while sleeping"),
    511: ("hype", "5 TRENDING IN TURKEY"),
    512: ("nostalgia", "8 years 😢 forever iconic song"),
    513: ("spam", "stream harder 30M as soon as possible"),
    514: ("hype", "1B before August 8th — we tried"),
    515: ("hype", "fall in love with Lisa"),
    516: ("opinion", "quoting producer Tommy Brown — industry insider endorsement"),
    517: ("spam", "OUR GOALS 400M + 500M viewer targets"),
    518: ("hype", "whose blinks and non-blinks active everyday"),
    519: ("nostalgia", "happy 8th anniversary record breaking masterpiece"),
    520: ("opinion", "strategic argument: AIIYL more important to stream than 4D"),
    521: ("hype", "blink and army best friends please stop fanwars"),
    522: ("nostalgia", "who's here in 2026 to support"),
    523: ("spam", "who came after Jennie Solo + 10M views call"),
    524: ("hype", "new album in November excitement"),
    525: ("opinion", "analyzing where hate comes from — antis not fandom"),
    526: ("opinion", "something big behind the mess — haters use immature blinks"),
    527: ("hype", "Lisa is my bias but love them all"),
    528: ("hype", "what blinks should do on IG advice"),
    529: ("hype", "Nao Blink Army XD Hello"),
    530: ("hype", "smiley reply"),
    531: ("hype", "o reply"),
    532: ("hype", "i will not absent ma'am joke"),
    533: ("hype", "present teacher joke"),
    534: ("nostalgia", "November 22nd 2020 date stamp"),
    535: ("hype", "me too reply"),
    536: ("nostalgia", "ya 2025 reply"),
    537: ("nostalgia", "Im 2020 november"),
    538: ("hype", "amo BLACK PINK"),
    539: ("hype", "no emoji please"),
    540: ("nostalgia", "hadir dari tahun 2024 — present from 2024"),
    541: ("hype", "yes girl reply"),
    542: ("hype", "I just came for DU DU DU DU DU"),
    543: ("hype", "hands up me mam"),
    544: ("hype", "blink flopada"),
    545: ("hype", "non-English Portuguese addicted to BLACKPINK"),
    546: ("hype", "TURKISH ARMY USA #1"),
    547: ("hype", "non-English Turkish found you"),
    548: ("hype", "TURKISH ARMY #10 now"),
    549: ("hype", "TURKISH ARMY now #10"),
    550: ("hype", "its now number in US"),
    551: ("hype", "non-English Vietnamese 30M reply"),
    552: ("hype", "non-English 30M reply"),
    553: ("hype", "done views frozen reply"),
    554: ("hype", "non-English 30M reply"),
    555: ("hype", "done reply"),
    556: ("hype", "30 MILLION VIEWS reply"),
    557: ("hype", "30M go check"),
    558: ("hype", "30 million go check"),
    559: ("hype", "WE DID IT"),
    560: ("hype", "impossible 950M before Aug 8th credible limit"),
    561: ("hype", "my birthday is the 8th we can do it"),
    562: ("hype", "happy birthday reply"),
    563: ("hype", "...... reply"),
    564: ("hype", "Kim Jennie reply"),
    565: ("spam", "we can do it 100M in two days coordination"),
    566: ("hype", "WE CAN DO IT 100% sure"),
    567: ("hype", "october 1B prediction"),
    568: ("hype", "impossible not in our vocabulary"),
    569: ("hype", "we always get 100M in first day argument"),
    570: ("hype", "we can do it BLINKS"),
    571: ("hype", "dots reply"),
    572: ("hype", "don't say impossible possible"),
    573: ("hype", "let's do it thank you"),
    574: ("criticism", "that's impossible lmao — realistic pushback"),
    575: ("criticism", "YG bribed YouTube conspiracy — critical of system"),
    576: ("criticism", "that's really unfair wtf reaction to conspiracy"),
    577: ("hype", "gibberish emoji"),
    578: ("criticism", "no hate but it won't reach 900M — realistic doubt"),
    579: ("hype", "it will we have days — rebuttal"),
    580: ("hype", "it actually will easily rebuttal"),
    581: ("hype", "it's 1B boyy XD"),
    582: ("hype", "all good but Lisa is #1 for me"),
    583: ("hype", "Lisa is my wife"),
    584: ("hype", "girlll??? reply"),
    585: ("hype", "Lisa forever my wife joke"),
    586: ("hype", "who doesn't reply"),
    587: ("hype", "Lisa is the most popular member"),
    588: ("opinion", "her outfit is a bit weird but still beautiful — specific aesthetic note"),
    589: ("hype", "LISAAAAAAA exclamation"),
    590: ("opinion", "all are good, OT4 matters — wouldn't be BP without all of them"),
    591: ("criticism", "talking about yourself stay pressed — dismissive comeback"),
    592: ("spam", "let's try to reach 140M call"),
    593: ("hype", "people who dislike the video reply"),
    594: ("hype", "I'm a girl but in love with Lisa"),
    595: ("hype", "SANE reply"),
    596: ("hype", "I fell in love with BlackPink"),
    597: ("hype", "Lisa is mine hahahaha"),
    598: ("hype", ""),
    599: ("hype", ""),
}

def main():
    with open("raw_comments.csv", newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    with open("dataset.csv", "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["text", "label", "notes"])
        writer.writeheader()
        for i, row in enumerate(rows):
            label, notes = LABELS.get(i, ("hype", ""))
            writer.writerow({"text": row["text"], "label": label, "notes": notes})

    # print distribution
    from collections import Counter
    with open("dataset.csv", newline="", encoding="utf-8") as f:
        labeled = list(csv.DictReader(f))
    counts = Counter(r["label"] for r in labeled)
    total = sum(counts.values())
    print(f"Total: {total}")
    for label, n in sorted(counts.items(), key=lambda x: -x[1]):
        print(f"  {label:<12} {n:>4}  ({n/total*100:.1f}%)")

if __name__ == "__main__":
    main()
